### ISSUE TITLE
There is no *ViewBehavior protocol file and definition

### ISSUE THREAD

**Issue by coneman** [happyfresh/hyper-viper-module-generator#1]
I tried to generate module using View Controller Module and View Module, but there is no header file nor definition for *ViewBehavior protocol.

**Comment by thidayatullah** [comment]
Fixed in https://github.com/happyfresh/hyper-viper-module-generator/commit/7da3919d37f5e8f59f0bbd19030360a2c4a27a1e

7da3919d37f5e8f59f0bbd19030360a2c4a27a1e
